import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import FixNavbar from "@/components/web/Nav/FixNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DROPEX - Make Your Email",
  description: "Generated by Mahamudul hasan Miyad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main suppressHydrationWarning className={``}>
      <FixNavbar />
      {children}
      <Footer />
      <Toaster />
    </main>
  );
}
