import { Toaster } from "@/components/ui/sonner";
import Layout from "@/layout/Layout";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Dropex-Bulk-Mailer",
  description: "Generated By Mioxdhropic ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`antialiased`} suppressHydrationWarning>
      <Layout>{children}</Layout>
      <Toaster />
    </main>
  );
}
