import ProtectedLayout from "@/components/DisableApp/Disable";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/Theme/theme-provider";
import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "DROPEX - Make Your Email",
  description: "Generated by Mahamudul hasan Miyad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${poppins.className}`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ProtectedLayout>{children}</ProtectedLayout>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
